server:
  port: 8888
spring:
  application:
    name: todo-central-config
  cloud:
    config:
      server:
        git:
          uri: file:/C:/God Root/Todo Config
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka}