spring:
  application:
    name: todo-central-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/giri-shhh/todo-config.git
          username: giri-shhh
          password: Mugiwara@077
          clone-on-start: true

server:
  port: 8888

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://todo-service-registry:8761/eureka